import './globals.css'
import { Inter } from 'next/font/google'
import FetchNarutoData from '@/components/FetchNarutoData'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Naruto nextjs app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <link rel='stylesheet' href='https://bootswatch.com/5/lux/bootstrap.min.css'></link>
    </head>
      <body className={inter.className}>
      
      <NavBar/>
      {children}
      <div>
        <FetchNarutoData/>
      </div>
      </body>
    </html>
  )
}
